
services:
    mongodb:
        image: mongo:latest
        container_name: taxicab_mongo
        restart: always
        environment: 
            MONGO_INITDB_ROOT_USERNAME: mongoAdmin
            MONGO_INITDB_ROOT_PASSWORD: PosLLy22pO7T4i
            MONGO_INITDB_DATABASE: taxicab
        volumes:
            - ./volume/data/:/data/db
            - ./volume/logs:/data/logs
            - ./volume/config:/data/configdb
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        ports: 
            - '27021:27017'
        network_mode: bridge